
SpecifyCoefUI <- function(id){
  
  ns <- NS(id)

    tabPanel("Specifying Coefficients",
             sidebarLayout(
               sidebarPanel(width = 3,
                            fluidRow(
                              selectInput(inputId = ns("model_type"),
                                          label = "Choose Type of Model",
                                          choices = c("One continuous predictor: y = b0 + b1x + eps" = "continuous", 
                                                      "One binary predictor: y = b0 + b1D + eps" = "binary", 
                                                      "One continuous predictor and one binary predictor (no interaction):
                                           y = a + b1*x + b2*D + eps" = "continuous+binary",
                                                      "One continuous predictor, one binary predictor and their interaction:
                                           y = a + b1*x + b2*D + b3*(x*D) + eps" = "continuous*binary")),
                              numericInput(inputId = ns("select_b0"), "Intercept (b0):", 1)),
                            
                            fluidRow(
                              conditionalPanel("input.model_type === 'continuous'", ns = ns,
                                               numericInput(inputId = ns("select_b1"), "Coefficient on X (b1):", 0.5)),
                              conditionalPanel("input.model_type === 'binary'", ns = ns,
                                               numericInput(inputId = ns("select_b1D"), "Coefficient on D (b1):", 0.5)),
                              conditionalPanel("input.model_type === 'continuous+binary'", ns = ns,
                                               numericInput(inputId = ns("select_b1p"), "Coefficient on X (b1):", 0.5),
                                               numericInput(inputId = ns("select_b2p"), "Coefficient on D (b2):", 0.5)),
                              conditionalPanel("input.model_type === 'continuous*binary'", ns = ns,
                                               numericInput(inputId = ns("select_b1m"), "Coefficient on X (b1):", 0.5),
                                               numericInput(inputId = ns("select_b2m"), "Coefficient on D (b2):", 0.5),
                                               numericInput(inputId = ns("select_b3m"), "Coefficient on X*D (b3):", 0.5))
                            ),
                            fluidRow(
                              conditionalPanel("input.model_type === 'continuous+binary' || input.model_type === 'continuous*binary' || input.model_type === 'continuous'", ns = ns,
                                               sliderInput(inputId = ns("x_range"),
                                                           label = "Range of x",
                                                           min = 0, max = 10, value = c(0, 1), step = 0.1, dragRange = T))
                            ),
                            fluidRow(
                              sliderInput(inputId = ns("sample_size"),
                                          label = "Select Sample Size",
                                          min = 10, max = 1000, value = 250, step = 10)
                            ),
                            fluidRow(
                              sliderInput(inputId = ns("epsilon_error"),
                                          label = "Define Residual Std Dev (sigma)",
                                          min = 0, max = 10, value = 0.3, step = 0.1)
                            ),
                            fluidRow(
                              h3("Include on Graph:"),
                              checkboxInput(inputId = ns("include_real_function"), 
                                            label = "Original Function", value = T),
                              checkboxInput(inputId = ns("include_geom_point"),
                                            label = "Points", value = T),
                              checkboxInput(inputId = ns("include_ci"),
                                            label = "Confidence interval", value = T),
                              checkboxInput(inputId = ns("include_pi"),
                                            label = "Prediction Interval", value = T),
                              checkboxInput(inputId = ns("include_fit"),
                                            label = "Model's fit", value = T)
                              
                            )),
               mainPanel(
                 tabsetPanel(
                   tabPanel("Introdution", fluidRow( tags$div(
                     style="margin: 50px 50px;",
                     p("In this module, you will learn how linear regression models fit on data. You can specify how your data is generated by setting coefficients, 
                     sample size, range of continuous variable and standard deviation of residual."),
                     p("The module includes four types of linear regression model:"),
                     tags$div(
                       tags$ul(
                         tags$li("Linear regression with one continuous predictor: y = b0 + b1x + \u03B5"),
                         tags$li("Linear regression with one binary predictor: y = b0 + b1D + \u03B5"),
                         tags$li("Linear regression with one continuous predictor and one binary predictor (no interaction):",
                                 tags$br(), "y = b0 + b1x + b2D + \u03B5"),
                         tags$li("Linear regression with one continuous predictor, one binary predictor and their interaction:", 
                                 tags$br(), "y = b0 + b1x + b2D + b3x*D + \u03B5")
                       )
                     )
                   )
                   
                   ))
                   ,
                   tabPanel("Fitting Models", fluidRow(tags$div(
                     style="margin: 20px 40px;",p("Change the input values on the left panel to see how the regression line changes.")),
                     plotOutput(outputId = ns("result_plot"), height = "500px"),
                     column(width = 6,
                            h3("Graph Legend:"),
                            p("Points: Randomized Sample"),
                            p("Solid Black & Solid Brown: Real Relationship"),
                            p("Solid Blue & Solid Red: Model Fit"),
                            p("Dashed Cyan & Dashed Purple: Confidence Intervals"),
                            p("Dashed Green & Dashed Orange: Prediction Interval")),
                     column(width = 6, 
                            h3("Interpretation:"),
                            textOutput(ns("formula")), 
                            textOutput(ns("interpretation")), br(),
                            conditionalPanel("input.model_type === 'continuous+binary' || input.model_type === 'continuous*binary'", ns = ns,
                                             textOutput(ns("another_explain0")), textOutput(ns("another_explain1")), textOutput(ns("another_explain2")),
                                             textOutput(ns("another_explain3")),textOutput(ns("another_explain4")),textOutput(ns("another_explain5")), br()))
                   ))
                   
                 )
               )))

  
}